version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "./server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "./clients/patient-overview"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "./clients/resource-graph"
    schedule:
      interval: "weekly"
      
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

