version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      
  - package-ecosystem: pip
    directory: /spreadsheet 
    schedule:
      interval: weekly
      day: tuesday


