services:
  fhir-name-service:
    build:
      context: ./services/fhir-name-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  patient-timeline:
    build:
      context: .
      dockerfile: services/patient-timeline/Dockerfile
    ports:
      - "4001:4001"
    network_mode: "host"
