services:
  overview:
    build:
      context: .
      dockerfile: overview/Dockerfile
    command: sh -c "python3 /workspace/overview/main.py && apache2-foreground"
    ports:
      - "1234:80"
    volumes:
      - ./overview:/var/www/html
      - ./:/workspace
    working_dir: /var/www/html
