services:
  fhir-data-db-cli:
    build:
      context: .
      dockerfile: cli/fhir-data-db-cli/Dockerfile
    depends_on:
      - fhir-data-db
    environment:
      PGHOST: fhir-data-db
      PGPORT: "5432"
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: fhir_db
    profiles:
      - fhir-db
      - search
