services:
  fhir-data-db:
    image: postgres:15
    container_name: fhir-data-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fhir_db
    ports:
      - "5432:5432"
    volumes:
      - fhir-data-db-data:/var/lib/postgresql/data
    profiles:
      - fhir-db
      - search

  fhir-data-db-tool:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: fhir-data-db
    ports:
      - "9091:8080"
    depends_on:
      - fhir-data-db
    profiles:
      - fhir-db
      - search

volumes:
  fhir-data-db-data:
