export const START_DATE = "1950-01-01" as const;

export const ORGANIZATIONS = 3;
export const PRACTITIONER_ROLES_PER_ORGANIZATION = 2;
export const PRACTITIONERS_PER_ORGANIZATION = 2;
export const PATIENTS_PER_PRACTITIONER = 4;
export const APPOINTMENTS_PER_PATIENT = 2;
export const EPISODES_PER_PATIENT = 4;
export const CONDITIONS_PER_PATIENT = 4;
export const ENCOUNTERS_PER_PATIENT = 20;
export const OBSERVATIONS_PER_ENCOUNTER = 2;

export const NUMBER_OF_ORGANIZATIONS = ORGANIZATIONS;
export const NUMBER_OF_PRACTITIONER_ROLES =
  PRACTITIONER_ROLES_PER_ORGANIZATION * ORGANIZATIONS;
export const NUMBER_OF_PRACTITIONERS = NUMBER_OF_PRACTITIONER_ROLES;
export const NUMBER_OF_PATIENTS =
  PATIENTS_PER_PRACTITIONER * NUMBER_OF_PRACTITIONERS;
export const NUMBER_OF_CONDITIONS = NUMBER_OF_PATIENTS * CONDITIONS_PER_PATIENT;
export const NUMBER_OF_EPISODES = NUMBER_OF_PATIENTS * EPISODES_PER_PATIENT;
export const NUMBER_OF_ENCOUNTERS = NUMBER_OF_PATIENTS * ENCOUNTERS_PER_PATIENT;
export const NUMBER_OF_OBSERVATIONS =
  NUMBER_OF_ENCOUNTERS * OBSERVATIONS_PER_ENCOUNTER;
export const NUMBER_OF_APPOINTMENTS =
  NUMBER_OF_PATIENTS * APPOINTMENTS_PER_PATIENT;

export const dummyDataConfig = {
  numberOfAppointments: NUMBER_OF_APPOINTMENTS,
  numberOfConditions: NUMBER_OF_CONDITIONS,
  numberOfEncounters: NUMBER_OF_ENCOUNTERS,
  numberOfEpisodes: NUMBER_OF_EPISODES,
  numberOfObservations: NUMBER_OF_OBSERVATIONS,
  numberOfOrganizations: NUMBER_OF_ORGANIZATIONS,
  numberOfPatients: NUMBER_OF_PATIENTS,
  numberOfPractitioners: NUMBER_OF_PRACTITIONERS,
  numberOfPractitionerRoles: NUMBER_OF_PRACTITIONER_ROLES,
  startDate: START_DATE,
};
