services:
  gp-search:
    build:
      context: ..
      dockerfile: gp-search/Dockerfile
    ports:
      - "5176:80"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - gp-search-db
    environment:
      DB_HOST: gp-search-db
      DB_NAME: gp_search
      DB_USER: gp_search_user
      DB_PASSWORD: gp_search_password

  gp-search-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: gp_search
      MYSQL_USER: gp_search_user
      MYSQL_PASSWORD: gp_search_password
      MYSQL_ROOT_PASSWORD: gp_search_root_password
    ports:
      - "3308:3306"
    volumes:
      - gp_search_data:/var/lib/mysql

  gp-search-phpmyadmin:
    image: phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: gp-search-db
    depends_on:
      - gp-search-db

volumes:
  gp_search_data:
