### Ping
GET http://localhost:3000/ping

### Sign up
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
  "username": "quux",
  "password": "bar",
  "role": "guest"
}

### Sign in (jacksparrow)
# @name signInJack
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "username": "jacksparrow",
  "password": "fooBar"
}

### Sign in
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
  "username": "quux",
  "password": "bar"
}

### Get users
GET http://localhost:3000/api/users/me
Authorization: Bearer {{signInJack.response.body.$.token}}

### Get users list via auth route
GET http://localhost:3000/api/users/list
Authorization: Bearer {{signInJack.response.body.$.token}}

### Get organizations via api route
GET http://localhost:3000/api/fhir/Organization
Authorization: Bearer {{signInJack.response.body.$.token}}

### Get organizations via api route
GET http://localhost:3000/api/fhir/Organization/5debcd22-6065-401c-9e84-4b9954a33cb8
Authorization: Bearer {{signInJack.response.body.$.token}}

### Get PractitionerRole with Practitioner id
GET http://localhost:3000/api/fhir/PractitionerRole
Authorization: Bearer {{signInJack.response.body.$.token}}

### Get Patients via api route
GET http://localhost:3000/api/fhir/Patient
Authorization: Bearer {{signInJack.response.body.$.token}}

### Get Episodes of Care via api route
GET http://localhost:3000/api/fhir/EpisodeOfCare
Authorization: Bearer {{signInJack.response.body.$.token}}