###
GET http://localhost:8080/api/v2/r5/Patient

###
GET http://localhost:8080/api/v2/r5/Patient?organization=Organization/organization-1

###
GET http://localhost:8080/api/v2/r5/Patient?general-practitioner=Practitioner/practitioner-1

###
GET http://localhost:8080/api/v2/r5/Patient?general-practitioner=Practitioner/practitioner-1&organization=Organization/organization-1

###
GET http://localhost:8080/api/v2/r5/Patient/patient-10
