###
GET http://localhost:8080/api/v2/r5/Patient

###
GET http://localhost:8080/api/v2/r5/Patient?organization=Organization/2f943eb6-b533-4d7d-a785-594b84832557

###
GET http://localhost:8080/api/v2/r5/Patient?general-practitioner=Practitioner/520e496d-094a-4b9e-993e-b0ca7b350ae0

###
GET http://localhost:8080/api/v2/r5/Patient/e676cee1-c2cd-401a-be44-29dd9f87ae92
