###
GET http://localhost:8080/api/v2/r5/Organization

###
GET http://localhost:8080/api/v2/r5/Organization/organization-2

###
POST http://localhost:8080/api/v2/r5/Organization
Content-Type:  application/json

{
  "name": "My Organization"
}

###
PATCH http://localhost:8080/api/v2/r5/Organization/542c4ada-b60a-4b2c-a3d3-51e4ed5079be
Content-Type:  application/json

{
  "name": "FooBar"
}