export const START_DATE = '1950-01-01';

export const NUMBER_OF_PATIENTS = 10;
export const NUMBER_OF_EPISODES_PER_PATIENT = 5;
export const NUMBER_OF_ENCOUNTERS_PER_PATIENT = 20;
export const NUMBER_OF_OBSERVATIONS_PER_ENCOUNTER = 2;
export const NUMBER_OF_ORGANIZATIONS = 4;
export const NUMBER_OF_PRACTITIONERS = 3;
