export const languages = [
  { code: "ar", system: "urn:ietf:bcp:47", display: "Arabisk" },
  { code: "bg", system: "urn:ietf:bcp:47", display: "Bulgarian" },
  { code: "bg-BG", system: "urn:ietf:bcp:47", display: "Bulgarian (Bulgaria)" },
  { code: "bn", system: "urn:ietf:bcp:47", display: "Bengali" },
  { code: "cs", system: "urn:ietf:bcp:47", display: "Czech" },
  { code: "cs-CZ", system: "urn:ietf:bcp:47", display: "Czech (Czechia)" },
  { code: "bs", system: "urn:ietf:bcp:47", display: "Bosnian" },
  {
    code: "bs-BA",
    system: "urn:ietf:bcp:47",
    display: "Bosnian (Bosnia and Herzegovina))",
  },
  { code: "da", system: "urn:ietf:bcp:47", display: "Danish" },
  { code: "da-DK", system: "urn:ietf:bcp:47", display: "Danish (Denmark)" },
  { code: "de", system: "urn:ietf:bcp:47", display: "German" },
  { code: "de-AT", system: "urn:ietf:bcp:47", display: "German (Austria)" },
  { code: "de-CH", system: "urn:ietf:bcp:47", display: "German (Switzerland)" },
  { code: "de-DE", system: "urn:ietf:bcp:47", display: "German (Germany)" },
  { code: "el", system: "urn:ietf:bcp:47", display: "Greek" },
  { code: "el-GR", system: "urn:ietf:bcp:47", display: "Greek (Greece)" },
  { code: "en", system: "urn:ietf:bcp:47", display: "English" },
  { code: "en-AU", system: "urn:ietf:bcp:47", display: "English (Australia)" },
  { code: "en-CA", system: "urn:ietf:bcp:47", display: "English (Canada)" },
  {
    code: "en-GB",
    system: "urn:ietf:bcp:47",
    display: "English (Great Britain)",
  },
  { code: "en-IN", system: "urn:ietf:bcp:47", display: "English (India)" },
  {
    code: "en-NZ",
    system: "urn:ietf:bcp:47",
    display: "English (New Zealand)",
  },
  { code: "en-SG", system: "urn:ietf:bcp:47", display: "English (Singapore)" },
  {
    code: "en-US",
    system: "urn:ietf:bcp:47",
    display: "English (United States)",
  },
  { code: "es", system: "urn:ietf:bcp:47", display: "Spanish" },
  { code: "es-AR", system: "urn:ietf:bcp:47", display: "Spanish (Argentina)" },
  { code: "es-ES", system: "urn:ietf:bcp:47", display: "Spanish (Spain)" },
  { code: "es-UY", system: "urn:ietf:bcp:47", display: "Spanish (Uruguay)" },
  { code: "et", system: "urn:ietf:bcp:47", display: "Estonian" },
  { code: "et-EE", system: "urn:ietf:bcp:47", display: "Estonian (Estonia)" },
  { code: "fi", system: "urn:ietf:bcp:47", display: "Finnish" },
  { code: "fr", system: "urn:ietf:bcp:47", display: "French" },
  { code: "fr-BE", system: "urn:ietf:bcp:47", display: "French (Belgium)" },
  { code: "fr-CH", system: "urn:ietf:bcp:47", display: "French (Switzerland)" },
  { code: "fr-FR", system: "urn:ietf:bcp:47", display: "French (France)" },
  { code: "fi-FI", system: "urn:ietf:bcp:47", display: "Finnish (Finland)" },
  { code: "fr-CA", system: "urn:ietf:bcp:47", display: "French (Canada)" },
  { code: "fy", system: "urn:ietf:bcp:47", display: "Frisian" },
  {
    code: "fy-NL",
    system: "urn:ietf:bcp:47",
    display: "Frisian (Netherlands)",
  },
  { code: "hi", system: "urn:ietf:bcp:47", display: "Hindi" },
  { code: "hr", system: "urn:ietf:bcp:47", display: "Croatian" },
  { code: "hr-HR", system: "urn:ietf:bcp:47", display: "Croatian (Croatia)" },
  { code: "is", system: "urn:ietf:bcp:47", display: "Icelandic" },
  { code: "is-IS", system: "urn:ietf:bcp:47", display: "Icelandic (Iceland)" },
  { code: "it", system: "urn:ietf:bcp:47", display: "Italian" },
  {
    code: "it-CH",
    system: "urn:ietf:bcp:47",
    display: "Italian (Switzerland)",
  },
  { code: "it-IT", system: "urn:ietf:bcp:47", display: "Italian (Italy)" },
  { code: "ja", system: "urn:ietf:bcp:47", display: "Japanese" },
  { code: "ko", system: "urn:ietf:bcp:47", display: "Korean" },
  { code: "lt", system: "urn:ietf:bcp:47", display: "Lithuanian" },
  {
    code: "lt-LT",
    system: "urn:ietf:bcp:47",
    display: "Lithuanian (Lithuania)",
  },
  { code: "lv", system: "urn:ietf:bcp:47", display: "Latvian" },
  { code: "lv-LV", system: "urn:ietf:bcp:47", display: "Latvian (Latvia)" },
  { code: "nl", system: "urn:ietf:bcp:47", display: "Dutch" },
  { code: "nl-BE", system: "urn:ietf:bcp:47", display: "Dutch (Belgium)" },
  { code: "nl-NL", system: "urn:ietf:bcp:47", display: "Dutch (Netherlands)" },
  { code: "no", system: "urn:ietf:bcp:47", display: "Norwegian" },
  { code: "no-NO", system: "urn:ietf:bcp:47", display: "Norwegian (Norway)" },
  { code: "pa", system: "urn:ietf:bcp:47", display: "Punjabi" },
  { code: "pl", system: "urn:ietf:bcp:47", display: "Polskie" },
  { code: "pl-PL", system: "urn:ietf:bcp:47", display: "Polish (Poland)" },
  { code: "pt", system: "urn:ietf:bcp:47", display: "Portuguese" },
  {
    code: "pt-PT",
    system: "urn:ietf:bcp:47",
    display: "Portuguese (Portugal)",
  },
  { code: "pt-BR", system: "urn:ietf:bcp:47", display: "Portuguese (Brazil)" },
  { code: "ro", system: "urn:ietf:bcp:47", display: "Romanian" },
  { code: "ro-RO", system: "urn:ietf:bcp:47", display: "Romanian (Romania)" },
  { code: "ru", system: "urn:ietf:bcp:47", display: "Russian" },
  { code: "ru-RU", system: "urn:ietf:bcp:47", display: "Russian (Russia)" },
  { code: "sk", system: "urn:ietf:bcp:47", display: "Slovakian" },
  { code: "sk-SK", system: "urn:ietf:bcp:47", display: "Slovakian (Slovakia)" },
  { code: "sl", system: "urn:ietf:bcp:47", display: "Slovenian" },
  { code: "sl-SI", system: "urn:ietf:bcp:47", display: "Slovenian (Slovenia)" },
  { code: "sr", system: "urn:ietf:bcp:47", display: "Serbian" },
  { code: "sr-RS", system: "urn:ietf:bcp:47", display: "Serbian (Serbia)" },
  { code: "sv", system: "urn:ietf:bcp:47", display: "Swedish" },
  { code: "sv-SE", system: "urn:ietf:bcp:47", display: "Swedish (Sweden)" },
  { code: "te", system: "urn:ietf:bcp:47", display: "Telugu" },
  { code: "zh", system: "urn:ietf:bcp:47", display: "Chinese" },
  { code: "zh-CN", system: "urn:ietf:bcp:47", display: "Chinese (China)" },
  { code: "zh-HK", system: "urn:ietf:bcp:47", display: "Chinese (Hong Kong)" },
  { code: "zh-SG", system: "urn:ietf:bcp:47", display: "Chinese (Singapore)" },
  { code: "zh-TW", system: "urn:ietf:bcp:47", display: "Chinese (Taiwan)" },
];
