###
GET http://localhost:8080/api/v2/r5/organizations

###
GET http://localhost:8080/api/v2/r5/organizations?name=Hand%20Inc

###
GET http://localhost:8080/api/v2/r5/organizations?name=unknown

###
GET http://localhost:8080/api/v2/r5/organizations?unknown=foo

###
GET http://localhost:8080/api/v2/r5/organizations/e676cee1-c2cd-401a-be44-29dd9f87ae92

###
POST http://localhost:8080/api/v2/r5/organizations
Content-Type:  application/json

{
  "name": "My Organization"
}

###
DELETE http://localhost:8080/api/v2/r5/organizations/90b2e19a-415d-4309-b19a-b6a7fa711cdf

###
PATCH http://localhost:8080/api/v2/r5/organizations/542c4ada-b60a-4b2c-a3d3-51e4ed5079be
Content-Type:  application/json

{
  "name": "FooBar"
}