export const Items = {
  ORGANIZATION: "ORGANIZATION",
  PRACTITIONER_ROLE: "PRACTITIONER_ROLE",
  PRACTITIONER: "PRACTITIONER",
  PATIENT: "PATIENT",
  CONDITION: "CONDITION",
  EPISODE_OF_CARE: "EPISODE_OF_CARE",
  ENCOUNTER: "ENCOUNTER",
  OBSERVATION: "OBSERVATION",
} as const;
