name: E2E

permissions:
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run E2E
        run: npm run test:e2e
