name: Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  unit:
    name: Unit Tests
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run test

  e2e:
    name: E2E
    uses: ./.github/workflows/node-ci.yml
    with:
      run-command: |
        npm run test:e2e
