name: Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  tests-client:
    name: Run Tests Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./client"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./client/.nvmrc"

      - name: Install dependencies
        run: npm install
      
      - name: Client - run unit Tests
        run: npm run test:unit

  tests-server:
    name: Run Tests Server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./server"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./server/.nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Server - run unit Tests
        run: npm run test:unit

      - name: Server - run E2E tests
        run: npm run test:e2e

