name: Tests

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./.nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Server - run unit Tests
        run: pnpm --filter ./server... run test:unit

      - name: Server - run E2E tests
        run: pnpm --filter ./server... run test:e2e
      
      - name: Client - run unit Tests
        run: pnpm --filter ./client... run test:unit
